# Generated by Django 3.1.8 on 2024-06-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='task_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
