# Generated by Django 3.1.8 on 2024-06-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_transaction_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='transaction',
            name='time_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
