# Generated by Django 5.0.6 on 2024-06-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_item_time_end_alter_item_time_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='completed',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('active', 'Active'), ('completed', 'Completed')], default='default', max_length=10),
        ),
    ]
