# Generated by Django 5.0.6 on 2024-06-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_item_completed_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='Rome', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='travel_industry',
            field=models.CharField(default='Hotel', max_length=100),
            preserve_default=False,
        ),
    ]
