# Generated by Django 5.0.6 on 2024-06-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_item_location_item_travel_industry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='location',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='item',
            name='travel_industry',
        ),
        migrations.AddField(
            model_name='item',
            name='all_info',
            field=models.JSONField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='results',
            field=models.JSONField(default='None'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('active', 'Active'), ('incorrect', 'Incorrect'), ('completed', 'Completed')], default='default', max_length=10),
        ),
    ]
