# Generated by Django 3.1.8 on 2024-06-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20240609_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('active', 'Active'), ('incorrect', 'Incorrect'), ('completed', 'Completed'), ('reported', 'Reported')], default='default', max_length=10),
        ),
    ]
