# Generated by Django 3.1.8 on 2024-07-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20240626_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bank_vist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('active', 'Active'), ('incorrect', 'Incorrect'), ('completed', 'Completed'), ('reported', 'Reported'), ('sucess', 'Sucess'), ('fail', 'Fail')], default='default', max_length=10),
        ),
    ]
