# Generated by Django 3.1.8 on 2024-07-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20240703_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('active', 'Active'), ('incorrect', 'Incorrect'), ('completed', 'Completed'), ('reported', 'Reported')], default='default', max_length=10),
        ),
    ]
