# Generated by Django 3.1.8 on 2024-07-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20240707_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='round_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='use_extention',
            field=models.BooleanField(default=False),
        ),
    ]
