# Generated by Django 3.1.8 on 2024-07-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20240707_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='use_extenstion',
            new_name='use_extension',
        ),
    ]
