# Generated by Django 3.1.8 on 2024-07-07 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20240707_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('results', models.BinaryField()),
                ('all_info', models.BinaryField()),
                ('message', models.CharField(max_length=100)),
                ('time_start', models.IntegerField(blank=True, null=True)),
                ('time_end', models.IntegerField(blank=True, null=True)),
                ('bank_vist', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('default', 'Default'), ('active', 'Active'), ('incorrect', 'Incorrect'), ('completed', 'Completed'), ('reported', 'Reported')], default='default', max_length=10)),
                ('phish', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('fail', 'Fail'), ('sucess', 'Sucess')], default='sucess', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
