# Generated by Django 3.1.8 on 2024-08-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_itemdump'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phish_type',
            field=models.CharField(default='url', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='itemdump',
            name='phish_type',
            field=models.CharField(default='url', max_length=10, null=True),
        ),
    ]
