# Generated by Django 3.1.8 on 2024-08-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20240801_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='long_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='long_term_group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
