# Generated by Django 3.1.8 on 2024-09-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_extension_id_alter_item_id_alter_itemdump_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='round_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemdump',
            name='round_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='phish_type',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='result',
            field=models.CharField(choices=[('fail', 'Fail'), ('sucess', 'Sucess')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('default', 'Default'), ('active', 'Active'), ('incorrect', 'Incorrect'), ('completed', 'Completed'), ('reported', 'Reported')], default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='task',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='itemdump',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
